-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- 코드를 입력하세요
SELECT
    PRODUCT.PRODUCT_CODE AS PRODUCT_CODE,
    SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE JOIN PRODUCT
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT_CODE;