-- https://school.programmers.co.kr/learn/courses/30/lessons/144854
-- 코드를 입력하세요
SELECT
    BOOK.BOOK_ID AS BOOK_ID,
    AUTHOR.AUTHOR_NAME AS AUTOR_NAME,
    DATE_FORMAT(BOOK.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM
    BOOK JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE
    CATEGORY = '경제'
ORDER BY
    PUBLISHED_DATE;